#############################网络状态#####################################

NetworkStatus_Closed = -1
NetworkStatus_Actived=0
NetworkStatus_Connecting=1
NetworkStatus_Connected=2
NetworkStatus_Ready=3
NetworkStatus_Established=4

###########################网络通信协议段##################################

PKTTYPE_AGV_SHELL=0x00010000
PKTTYPE_ACK=0x80000000

PKTTYPE_AGV_SHELL_PRE_LOGIN=0x00000001 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_PRE_LOGIN_ACK=PKTTYPE_AGV_SHELL_PRE_LOGIN | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_LOGIN=0x00000002 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_LOGIN_ACK=PKTTYPE_AGV_SHELL_LOGIN | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_KEEPALIVE=0x00000003 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_KEEPALIVE_ACK=PKTTYPE_AGV_SHELL_KEEPALIVE | PKTTYPE_ACK

#Status CmdList
PKTTYPE_AGV_SHELL_GET_PROCESS_LIST=0x00000005 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_GET_PROCESS_LIST_ACK = PKTTYPE_AGV_SHELL_GET_PROCESS_LIST | PKTTYPE_ACK
#UpdateCmdList
PKTTYPE_AGV_SHELL_SET_PROCESS_LIST=0x00000006 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_SET_PROCESS_LIST_ACK=PKTTYPE_AGV_SHELL_SET_PROCESS_LIST | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_PROCESS_COMMAND = 0x00000007 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_PROCESS_COMMAND_ACK = PKTTYPE_AGV_SHELL_PROCESS_COMMAND | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_UPDATE_NTP = 0x00000202 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_UPDATE_NTP_ACK = PKTTYPE_AGV_SHELL_UPDATE_NTP | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_FILE_MUTEX_STATUS = 0x00000208 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_FILE_MUTEX_STATUS_ACK = PKTTYPE_AGV_SHELL_FILE_MUTEX_STATUS | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_MODIFY_FILE_MUTEX = 0x00000209 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_MODIFY_FILE_MUTEX_ACK = PKTTYPE_AGV_SHELL_MODIFY_FILE_MUTEX | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_GET_FIXED_SYSINFO = 0x0000020F | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_GET_FIXED_SYSINFO_ACK = PKTTYPE_AGV_SHELL_GET_FIXED_SYSINFO | PKTTYPE_ACK



#file transform
PKTTYPE_AGV_SHELL_GET_CATALOG_INFO = 0x00000301 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_GET_CATALOG_INFO_ACK = PKTTYPE_AGV_SHELL_GET_CATALOG_INFO | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_PUSH_FILE_HEAD = 0x00000302 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_PUSH_FILE_HEAD_ACK = PKTTYPE_AGV_SHELL_PUSH_FILE_HEAD | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_PUSH_FILE_BLOCK = 0x00000303 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_PUSH_FILE_BLOCK_ACK = PKTTYPE_AGV_SHELL_PUSH_FILE_BLOCK | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_READ_FILE_HEAD = 0x00000304 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_READ_FILE_HEAD_ACK = PKTTYPE_AGV_SHELL_READ_FILE_HEAD | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_READ_FILE_BLOCK = 0x00000305 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_READ_FILE_BLOCK_ACK = PKTTYPE_AGV_SHELL_READ_FILE_BLOCK | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_RW_FILE_STATUS = 0x00000307 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_RW_FILE_STATUS_ACK = PKTTYPE_AGV_SHELL_RW_FILE_STATUS | PKTTYPE_ACK


PKTTYPE_AGV_SHELL_UPGRADE = 0x0000020C | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_UPGRADE_ACK = PKTTYPE_AGV_SHELL_UPGRADE | PKTTYPE_ACK

#black_box
PKTTYPE_AGV_SHELL_GET_LOG_TYPE = 0x00000205| PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_GET_LOG_TYPE_ACK = PKTTYPE_AGV_SHELL_GET_LOG_TYPE | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_GET_LOG_FILE_NAME = 0x00000206 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_GET_LOG_FILE_NAME_ACK = PKTTYPE_AGV_SHELL_GET_LOG_FILE_NAME | PKTTYPE_ACK

PKTTYPE_AGV_SHELL_CANCEL_GET_LOG = 0x00000207 | PKTTYPE_AGV_SHELL
PKTTYPE_AGV_SHELL_CANCEL_GET_LOG_ACK = PKTTYPE_AGV_SHELL_CANCEL_GET_LOG | PKTTYPE_ACK
